#!/usr/bin/env python3
import os
import argparse
import subprocess
import re
import json


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('example', help='Directory containing example')
    args = parser.parse_args()
    if not os.path.isdir(args.example):
        sys.exit('sample directory %s does not exist' % args.example)

    for name in ('kea.log', 'kea.log.lock'):
        path = os.path.join(args.example, name)
        if os.path.exists(path):
            os.remove(path)

    conf = os.path.abspath(os.path.join(args.example, 'kea.conf'))
    try:
        cmd = '/usr/local/sbin/kea-dhcp4 -c ' + conf
        print(cmd)
        subprocess.call(cmd, shell=True)
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
